# Use a base image with Java installed
FROM openjdk:17-jdk-alpine
  
  # Set the working directory inside the container
WORKDIR /app
  
  # Copy the JAR file into the container
COPY target/employee-management-system.jar /app/employee-management-system.jar
  
  # Specify the command to run the JAR file
ENTRYPOINT ["java", "-jar", "employee-management-system.jar"]
